# See config.example.yml for documentation.

object: sys/main.dol
object_base: orig/RUUE01
extract_objects: true

# Change this to match the linker version.
# See config.example.yml for a list.
mw_comment_version: 14
symbols: config/RUUE01/symbols.txt
splits: config/RUUE01/splits.txt
skip_cfa_ranges:
  - start: .text:0x8033B644
    end: .text:0x8033B6B0
section_aliases:
  .bss2: .sbss
